server:
  port: 9729
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql : true
  datasource:
    url: jdbc:mysql://localhost:3306/study?characterEncoding=UTF-8&ServerTimezone=UTC
    username: root
    password: 9722
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true


